# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt-lightspeed-pos-vc-connector/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 786)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"font-size: 14px;\n"
"font-family: Roboto;\n"
"}\n"
"\n"
"QComboBox {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton {\n"
"color: white;\n"
"background-color: rgb(128, 128, 128);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 14px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 50px;\n"
"min-height: 16px;\n"
"max-height: 16px;\n"
"}\n"
"")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lbl_SyncLog = QtWidgets.QLabel(self.centralWidget)
        self.lbl_SyncLog.setGeometry(QtCore.QRect(20, 50, 60, 16))
        self.lbl_SyncLog.setObjectName("lbl_SyncLog")
        self.tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs.setGeometry(QtCore.QRect(20, 290, 631, 421))
        self.tabs.setStyleSheet("")
        self.tabs.setObjectName("tabs")
        self.tab_Sync = QtWidgets.QWidget()
        self.tab_Sync.setObjectName("tab_Sync")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_Sync)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 611, 181))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.combo_SyncVCUserType = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.combo_SyncVCUserType.setObjectName("combo_SyncVCUserType")
        self.combo_SyncVCUserType.addItem("")
        self.combo_SyncVCUserType.addItem("")
        self.combo_SyncVCUserType.addItem("")
        self.gridLayout_3.addWidget(self.combo_SyncVCUserType, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.checkBox_SyncChangesAfterDate = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_SyncChangesAfterDate.setObjectName("checkBox_SyncChangesAfterDate")
        self.gridLayout_3.addWidget(self.checkBox_SyncChangesAfterDate, 1, 1, 1, 1)
        self.dateEdit_SyncUpdatedAfterDate = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEdit_SyncUpdatedAfterDate.setObjectName("dateEdit_SyncUpdatedAfterDate")
        self.gridLayout_3.addWidget(self.dateEdit_SyncUpdatedAfterDate, 2, 1, 1, 1)
        self.combo_SyncGradeLevel = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.combo_SyncGradeLevel.setObjectName("combo_SyncGradeLevel")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.combo_SyncGradeLevel.addItem("")
        self.gridLayout_3.addWidget(self.combo_SyncGradeLevel, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_Sync)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 340, 611, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_SyncAllUsers = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_SyncAllUsers.setObjectName("btn_SyncAllUsers")
        self.gridLayout_2.addWidget(self.btn_SyncAllUsers, 0, 0, 1, 1)
        self.btn_DeleteVCUsers = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_DeleteVCUsers.setObjectName("btn_DeleteVCUsers")
        self.gridLayout_2.addWidget(self.btn_DeleteVCUsers, 0, 1, 1, 1)
        self.tabs.addTab(self.tab_Sync, "")
        self.functionsTab = QtWidgets.QWidget()
        self.functionsTab.setObjectName("functionsTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.functionsTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 340, 611, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_GetCustomerTypes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_GetCustomerTypes.setObjectName("btn_GetCustomerTypes")
        self.horizontalLayout.addWidget(self.btn_GetCustomerTypes)
        self.btn_GetPaymentTypes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_GetPaymentTypes.setObjectName("btn_GetPaymentTypes")
        self.horizontalLayout.addWidget(self.btn_GetPaymentTypes)
        self.btn_ExportCharges = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_ExportCharges.setObjectName("btn_ExportCharges")
        self.horizontalLayout.addWidget(self.btn_ExportCharges)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.functionsTab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 611, 321))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_CustType = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lbl_CustType.setObjectName("lbl_CustType")
        self.gridLayout_4.addWidget(self.lbl_CustType, 1, 0, 1, 1)
        self.btn_ExportFolderPicker = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_ExportFolderPicker.setObjectName("btn_ExportFolderPicker")
        self.gridLayout_4.addWidget(self.btn_ExportFolderPicker, 6, 0, 1, 1)
        self.line_ExportFolder = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.line_ExportFolder.setObjectName("line_ExportFolder")
        self.gridLayout_4.addWidget(self.line_ExportFolder, 6, 1, 1, 1)
        self.chk_ClearCharges = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.chk_ClearCharges.setText("")
        self.chk_ClearCharges.setChecked(True)
        self.chk_ClearCharges.setObjectName("chk_ClearCharges")
        self.gridLayout_4.addWidget(self.chk_ClearCharges, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.combo_PaymentType = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.combo_PaymentType.setObjectName("combo_PaymentType")
        self.gridLayout_4.addWidget(self.combo_PaymentType, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.combo_CustomerType = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.combo_CustomerType.setObjectName("combo_CustomerType")
        self.gridLayout_4.addWidget(self.combo_CustomerType, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 0, 1, 1)
        self.dateEdit_BeginExportRange = QtWidgets.QDateEdit(self.gridLayoutWidget_4)
        self.dateEdit_BeginExportRange.setObjectName("dateEdit_BeginExportRange")
        self.gridLayout_4.addWidget(self.dateEdit_BeginExportRange, 4, 1, 1, 1)
        self.dateEdit_EndExportRange = QtWidgets.QDateEdit(self.gridLayoutWidget_4)
        self.dateEdit_EndExportRange.setObjectName("dateEdit_EndExportRange")
        self.gridLayout_4.addWidget(self.dateEdit_EndExportRange, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.chk_ExportSaleLinesEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.chk_ExportSaleLinesEnabled.setText("")
        self.chk_ExportSaleLinesEnabled.setChecked(True)
        self.chk_ExportSaleLinesEnabled.setObjectName("chk_ExportSaleLinesEnabled")
        self.gridLayout_4.addWidget(self.chk_ExportSaleLinesEnabled, 3, 1, 1, 1)
        self.tabs.addTab(self.functionsTab, "")
        self.tab_Settings = QtWidgets.QWidget()
        self.tab_Settings.setObjectName("tab_Settings")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_Settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.txt_SettingsFileLocation = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_SettingsFileLocation.setObjectName("txt_SettingsFileLocation")
        self.gridLayout.addWidget(self.txt_SettingsFileLocation, 0, 1, 1, 1)
        self.lbl_SettingsFileLocation = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_SettingsFileLocation.setObjectName("lbl_SettingsFileLocation")
        self.gridLayout.addWidget(self.lbl_SettingsFileLocation, 0, 0, 1, 1)
        self.txt_LSAccountID = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_LSAccountID.setObjectName("txt_LSAccountID")
        self.gridLayout.addWidget(self.txt_LSAccountID, 1, 1, 1, 1)
        self.txt_LSDevelID = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_LSDevelID.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_LSDevelID.setObjectName("txt_LSDevelID")
        self.gridLayout.addWidget(self.txt_LSDevelID, 2, 1, 1, 1)
        self.txt_DevelSecret = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_DevelSecret.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_DevelSecret.setObjectName("txt_DevelSecret")
        self.gridLayout.addWidget(self.txt_DevelSecret, 3, 1, 1, 1)
        self.txt_RefreshToken = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_RefreshToken.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_RefreshToken.setObjectName("txt_RefreshToken")
        self.gridLayout.addWidget(self.txt_RefreshToken, 4, 1, 1, 1)
        self.txt_VCUser = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_VCUser.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_VCUser.setObjectName("txt_VCUser")
        self.gridLayout.addWidget(self.txt_VCUser, 5, 1, 1, 1)
        self.txt_VCPass = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_VCPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_VCPass.setObjectName("txt_VCPass")
        self.gridLayout.addWidget(self.txt_VCPass, 6, 1, 1, 1)
        self.txt_VCAPIURL = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_VCAPIURL.setObjectName("txt_VCAPIURL")
        self.gridLayout.addWidget(self.txt_VCAPIURL, 7, 1, 1, 1)
        self.btn_SaveSettings = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_SaveSettings.setObjectName("btn_SaveSettings")
        self.gridLayout.addWidget(self.btn_SaveSettings, 8, 1, 1, 1)
        self.tabs.addTab(self.tab_Settings, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 611, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.txt_ChangeUpdatePassword = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_ChangeUpdatePassword.setObjectName("txt_ChangeUpdatePassword")
        self.verticalLayout.addWidget(self.txt_ChangeUpdatePassword)
        self.btn_ChangeEncPassword = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_ChangeEncPassword.setObjectName("btn_ChangeEncPassword")
        self.verticalLayout.addWidget(self.btn_ChangeEncPassword)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(180, 20, 231, 41))
        self.label_17.setObjectName("label_17")
        self.tabs.addTab(self.tab, "")
        self.tab_Authorize = QtWidgets.QWidget()
        self.tab_Authorize.setObjectName("tab_Authorize")
        self.lbl_AuthorizeApp = QtWidgets.QLabel(self.tab_Authorize)
        self.lbl_AuthorizeApp.setGeometry(QtCore.QRect(260, 20, 91, 20))
        self.lbl_AuthorizeApp.setStyleSheet("")
        self.lbl_AuthorizeApp.setTextFormat(QtCore.Qt.RichText)
        self.lbl_AuthorizeApp.setOpenExternalLinks(True)
        self.lbl_AuthorizeApp.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lbl_AuthorizeApp.setObjectName("lbl_AuthorizeApp")
        self.txt_CodeReturned = QtWidgets.QLineEdit(self.tab_Authorize)
        self.txt_CodeReturned.setGeometry(QtCore.QRect(160, 100, 301, 21))
        self.txt_CodeReturned.setObjectName("txt_CodeReturned")
        self.lbl_AuthorizeCodeReturned = QtWidgets.QLabel(self.tab_Authorize)
        self.lbl_AuthorizeCodeReturned.setGeometry(QtCore.QRect(200, 40, 211, 61))
        self.lbl_AuthorizeCodeReturned.setTextFormat(QtCore.Qt.RichText)
        self.lbl_AuthorizeCodeReturned.setWordWrap(True)
        self.lbl_AuthorizeCodeReturned.setObjectName("lbl_AuthorizeCodeReturned")
        self.btn_Authorize = QtWidgets.QPushButton(self.tab_Authorize)
        self.btn_Authorize.setGeometry(QtCore.QRect(250, 350, 121, 24))
        self.btn_Authorize.setObjectName("btn_Authorize")
        self.txt_AuthorizeReturnedRefreshToken = QtWidgets.QLineEdit(self.tab_Authorize)
        self.txt_AuthorizeReturnedRefreshToken.setGeometry(QtCore.QRect(160, 170, 301, 21))
        self.txt_AuthorizeReturnedRefreshToken.setObjectName("txt_AuthorizeReturnedRefreshToken")
        self.label_15 = QtWidgets.QLabel(self.tab_Authorize)
        self.label_15.setGeometry(QtCore.QRect(160, 150, 301, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_Authorize)
        self.label_16.setGeometry(QtCore.QRect(160, 200, 301, 141))
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.tabs.addTab(self.tab_Authorize, "")
        self.txtb_SyncLog = QtWidgets.QTextEdit(self.centralWidget)
        self.txtb_SyncLog.setGeometry(QtCore.QRect(20, 80, 631, 201))
        self.txtb_SyncLog.setObjectName("txtb_SyncLog")
        self.lbl_Icon = QtWidgets.QLabel(self.centralWidget)
        self.lbl_Icon.setGeometry(QtCore.QRect(500, 10, 150, 59))
        self.lbl_Icon.setObjectName("lbl_Icon")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 663, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lightspeed Veracross Connector"))
        self.lbl_SyncLog.setText(_translate("MainWindow", "Log:"))
        self.combo_SyncVCUserType.setItemText(0, _translate("MainWindow", "Select Type"))
        self.combo_SyncVCUserType.setItemText(1, _translate("MainWindow", "Faculty Staff"))
        self.combo_SyncVCUserType.setItemText(2, _translate("MainWindow", "Students"))
        self.label_3.setText(_translate("MainWindow", "VC User Type"))
        self.label_14.setText(_translate("MainWindow", "Only Include Changes After Specified Date"))
        self.checkBox_SyncChangesAfterDate.setText(_translate("MainWindow", "Enable"))
        self.dateEdit_SyncUpdatedAfterDate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.combo_SyncGradeLevel.setItemText(0, _translate("MainWindow", "None"))
        self.combo_SyncGradeLevel.setItemText(1, _translate("MainWindow", "Kindergarten"))
        self.combo_SyncGradeLevel.setItemText(2, _translate("MainWindow", "Pre-Kindergarten"))
        self.combo_SyncGradeLevel.setItemText(3, _translate("MainWindow", "Grade 1"))
        self.combo_SyncGradeLevel.setItemText(4, _translate("MainWindow", "Grade 2"))
        self.combo_SyncGradeLevel.setItemText(5, _translate("MainWindow", "Grade 3"))
        self.combo_SyncGradeLevel.setItemText(6, _translate("MainWindow", "Grade 4"))
        self.combo_SyncGradeLevel.setItemText(7, _translate("MainWindow", "Grade 5"))
        self.combo_SyncGradeLevel.setItemText(8, _translate("MainWindow", "Grade 6"))
        self.combo_SyncGradeLevel.setItemText(9, _translate("MainWindow", "Grade 7"))
        self.combo_SyncGradeLevel.setItemText(10, _translate("MainWindow", "Grade 8"))
        self.combo_SyncGradeLevel.setItemText(11, _translate("MainWindow", "Grade 9"))
        self.combo_SyncGradeLevel.setItemText(12, _translate("MainWindow", "Grade 10"))
        self.combo_SyncGradeLevel.setItemText(13, _translate("MainWindow", "Grade 11"))
        self.combo_SyncGradeLevel.setItemText(14, _translate("MainWindow", "Grade 12"))
        self.label_19.setText(_translate("MainWindow", "Limit Sync to Grade Level"))
        self.btn_SyncAllUsers.setToolTip(_translate("MainWindow", "Syncs all VC users with Lightspeed"))
        self.btn_SyncAllUsers.setStatusTip(_translate("MainWindow", "Syncs all VC users with Lightspeed"))
        self.btn_SyncAllUsers.setText(_translate("MainWindow", "Sync Users"))
        self.btn_DeleteVCUsers.setToolTip(_translate("MainWindow", "Delete all users no longer found in VC"))
        self.btn_DeleteVCUsers.setStatusTip(_translate("MainWindow", "Delete all users no longer found in VC"))
        self.btn_DeleteVCUsers.setText(_translate("MainWindow", "Delete Inactive VC Users"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_Sync), _translate("MainWindow", "Sync"))
        self.btn_GetCustomerTypes.setText(_translate("MainWindow", "Refresh Cust Types"))
        self.btn_GetPaymentTypes.setText(_translate("MainWindow", "Refresh Pay Types"))
        self.btn_ExportCharges.setText(_translate("MainWindow", "Begin Export"))
        self.lbl_CustType.setText(_translate("MainWindow", "Customer Type"))
        self.btn_ExportFolderPicker.setText(_translate("MainWindow", "Export Folder"))
        self.label.setText(_translate("MainWindow", "Clear Charges After Export"))
        self.label_2.setText(_translate("MainWindow", "Clearing Payment Type"))
        self.combo_CustomerType.setToolTip(_translate("MainWindow", "Select customer type to export."))
        self.combo_CustomerType.setStatusTip(_translate("MainWindow", "Select customer type to export."))
        self.label_12.setText(_translate("MainWindow", "Begin Date Range"))
        self.dateEdit_BeginExportRange.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.dateEdit_EndExportRange.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_13.setText(_translate("MainWindow", "End Date Range"))
        self.label_4.setText(_translate("MainWindow", "Export SaleLines"))
        self.tabs.setTabText(self.tabs.indexOf(self.functionsTab), _translate("MainWindow", "Export"))
        self.label_7.setText(_translate("MainWindow", "VC Username"))
        self.label_8.setText(_translate("MainWindow", "VC Password"))
        self.label_6.setText(_translate("MainWindow", "LS Developer Client Secret"))
        self.label_11.setText(_translate("MainWindow", "LS Refresh Token"))
        self.label_10.setText(_translate("MainWindow", "LS AccountID"))
        self.label_5.setText(_translate("MainWindow", "LS Developer Client ID"))
        self.label_9.setText(_translate("MainWindow", "VC API URL"))
        self.lbl_SettingsFileLocation.setText(_translate("MainWindow", "Settings File"))
        self.btn_SaveSettings.setText(_translate("MainWindow", "Save Settings"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_Settings), _translate("MainWindow", "Settings"))
        self.label_18.setText(_translate("MainWindow", "Enter New Password (10 characters min)"))
        self.btn_ChangeEncPassword.setText(_translate("MainWindow", "Change Password"))
        self.label_17.setText(_translate("MainWindow", "Change Settings Encryption Password"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "Password"))
        self.lbl_AuthorizeApp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a href=\"https://cloud.lightspeedapp.com/oauth/authorize.php?scope=employee:all&amp;response_type=code&amp;client_id=__CLIENT_ID__\"><span style=\" text-decoration: underline; color:#0000ff;\">Authorize Link</span></a></p></body></html>"))
        self.lbl_AuthorizeCodeReturned.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Code Returned</p><p align=\"center\">Copy and Paste from URL</p></body></html>"))
        self.btn_Authorize.setText(_translate("MainWindow", "Authorize"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">LS Refresh Token Returned</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Copy and paste the refresh token returned from Lightspeed into your Refresh Token setting on the settings tab. </p><p align=\"center\">Be sure to update the account number from Lightspeed as well.</p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_Authorize), _translate("MainWindow", "Authorize App"))
        self.lbl_Icon.setText(_translate("MainWindow", "icon"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

